apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Health_Recipe
  region: ap-southeast-1

vpc:
  id: vpc-0a5969c5b7ec77ee2  # 你的VPC ID
  subnets:
    private:
      ap-southeast-1b:
        id: subnet-0a078081c86b25e6a
      ap-southeast-1c:
        id: subnet-0114c63907ba90a40
      ap-southeast-1a:
        id: subnet-0e1823e03600ed3b2
  securityGroup: sg-0d4abf60c70f62dd4  # 你的集群安全组ID

nodeGroups:
  - name: HealthRecipeNodes
    instanceType: t4g.nano
    desiredCapacity: 7
    minSize: 1
    maxSize: 7
    privateNetworking: true  # 使用私有子网