apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 381492195384.dkr.ecr.ap-southeast-1.amazonaws.com/health/gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gateway-config
        - secretRef:
            name: gateway-secret
        resources:
          requests:
            memory: "128Mi"         # Pod 最小需要的内存
            cpu: "250m"             # Pod 最小需要的 CPU
          limits:
            memory: "256Mi"         # Pod 最大允许的内存
            cpu: "500m"             # Pod 最大允许的 CPU