apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer  # 更改为 LoadBalancer 类型
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80          # 服务端口
      targetPort: 8080   # 容器内部端口