apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::381492195384:role/flux-ecr-access-role"
