apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: image-update-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-repo  # Ensure this points to your GitOps repository
  git:
    commit:
      author:
        email: "github-actions[bot]@users.noreply.github.com"
        name: "github-actions[bot]"
  update:
    path: "/cluster"  # Path to the GitOps manifests
    strategy: Setters
