apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/nusissSEteam9/git-ops.git 
  ref:
    branch: main
  secretRef:
    name: flux-git-auth  
