apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  JWT_SECRET: YlhsVGRYQmxjbE5sWTNKbGRFdGxlVUZpYjNabE16SkRhR0Z5WVdOMFpYSnpRVzVrVEc5dVp3PT0=
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL2lzcy1wcmFjdGljZS1tb2R1bGUuY2pxMncwY3dxYjVoLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjMzMDYvSEVBTFRIWVJFQ0lQWQ==
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: PVg1OWg1aVM8Z052S0hSKw==