apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
    spec:
      containers:
      - name: recipe
        image: 381492195384.dkr.ecr.ap-southeast-1.amazonaws.com/health/gateway:recipe-2de7b3b5cd3898169435488e8fbc4361b1d616c2
        ports:
        - containerPort: 8081
        env:
        # 引用 gateway-config ConfigMap 中的变量
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: gateway-config   # 引用同一个 ConfigMap
              key: SPRING_APPLICATION_NAME
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: USER_SERVICE_URL
        - name: ADMIN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: ADMIN_SERVICE_URL
        - name: RECIPE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: RECIPE_SERVICE_URL
        - name: EMAIL_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: EMAIL_SERVICE_URL
        - name: REPORT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: REPORT_SERVICE_URL
        - name: REVIEW_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: REVIEW_SERVICE_URL
        # 引用 gateway-secret Secret 中的变量
        - name: JWT_SECRET
          valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: JWT_SECRET
        - name: SPRING_DATASOURCE_URL
          valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: SPRING_DATASOURCE_PASSWORD
        # 配置资源限制
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"