apiVersion: v1
kind: Service
metadata:
  name: email-service           # 服务名称，可以用来通过 DNS 访问
spec:
  type: ClusterIP              # 如果只在集群内部访问，使用 ClusterIP
  selector:
    app: email                  # 选择器与 Deployment 中的标签匹配
  ports:
    - protocol: TCP
      port: 80                 # 公开的端口
      targetPort: 8081         # 容器内部的端口