apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       json
    [OUTPUT]
        Name         cloudwatch_logs
        Match        *
        region       ap-southeast-1
        log_group_name HR_logs
        log_stream_name {instance_id}
    Parsers_File /fluent-bit/etc/parsers.conf
  parsers.conf: |
    [PARSER]
        Name         json
        Format       json
