apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
        env:
          - name: FLUENT_CLOUDWATCH_LOG_GROUP
            value: "HR_logs"
          - name: AWS_REGION
            value: "ap-southeast-1"
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
        volumeMounts:
          - name: varlog
            mountPath: /var/log/containers
          - name: config-volume
            mountPath: /fluent-bit/etc/
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/containers
        - name: config-volume
          configMap:
            name: fluent-bit-config